package com.example.ui.localization

object Translator {
    val EN = mapOf(
        "app_title" to "Income Tracker",
        "dashboard" to "Dashboard",
        "analytics" to "Analytics",
        "reports" to "Reports",
        "settings" to "Settings",
        "about" to "About",
        "total_income" to "Total Income",
        "total_expense" to "Total Expense",
        "current_balance" to "Current Balance",
        "recent_transactions" to "Recent Transactions",
        "no_transactions" to "No transactions found",
        "add_transaction" to "Add Transaction",
        "edit_transaction" to "Edit Transaction",
        "add" to "Add",
        "edit" to "Edit",
        "save" to "Save",
        "delete" to "Delete",
        "cancel" to "Cancel",
        "title" to "Title / Note",
        "amount" to "Amount",
        "type" to "Type",
        "income" to "Income",
        "expense" to "Expense",
        "category" to "Category",
        "date" to "Date",
        "time" to "Time",
        "payment_method" to "Payment Method",
        "description" to "Description (Optional)",
        "custom_category" to "Custom Category",
        "create_category" to "Create Category",
        "category_name" to "Category Name",
        "select_type" to "Select Type",
        "reset_data" to "Reset Data",
        "reset_warning" to "Are you sure you want to delete all transactions? This action is permanent.",
        "backup_restore" to "Backup & Restore",
        "backup_success" to "Backup saved successfully!",
        "restore_success" to "Data restored successfully!",
        "backup_failed" to "Backup failed",
        "restore_failed" to "Restore failed",
        "all" to "All",
        "filter" to "Filter",
        "search" to "Search...",
        "weekly" to "Weekly Spending",
        "monthly" to "Monthly Spending",
        "category_wise" to "Category-wise Spending",
        "time_filter" to "Time Filter",
        "export_report" to "Export Report",
        "share_report" to "Share Report",
        "save_locally" to "Save Locally",
        "pin_lock" to "PIN Lock (4 Digits)",
        "biometric_lock" to "Biometric Lock",
        "dark_mode" to "Dark Mode",
        "language" to "Language (ভাষা)",
        "currency" to "Currency",
        "about_text" to "This application was built with maximum attention to visual details and user privacy. All of your financial data remains 100% offline on your device queryable inside Room SQL storage safely.",
        "about_author" to "Created by Abdullah Al Fahim"
    )

    val BN = mapOf(
        "app_title" to "ইনকাম ট্র্যাকার",
        "dashboard" to "ড্যাশবোর্ড",
        "analytics" to "বিশ্লেষণ",
        "reports" to "রিপোর্ট",
        "settings" to "সেটিংস",
        "about" to "সম্পর্কে",
        "total_income" to "মোট আয়",
        "total_expense" to "মোট ব্যয়",
        "current_balance" to "বর্তমান ব্যালেন্স",
        "recent_transactions" to "সাম্প্রতিক লেনদেন",
        "no_transactions" to "কোনো লেনদেন পাওয়া যায়নি",
        "add_transaction" to "লেনদেন যোগ করুন",
        "edit_transaction" to "লেনদেন সংশোধন",
        "add" to "যোগ",
        "edit" to "সংশোধন",
        "save" to "সংরক্ষণ",
        "delete" to "মুছে ফেলুন",
        "cancel" to "বাতিল",
        "title" to "শিরোনাম / নোট",
        "amount" to "পরিমাণ",
        "type" to "ধরন",
        "income" to "আয়",
        "expense" to "ব্যয়",
        "category" to "ক্যাটেগরি",
        "date" to "তারিখ",
        "time" to "সময়",
        "payment_method" to "পেমেন্ট মাধ্যম",
        "description" to "বিবরণ (ঐচ্ছিক)",
        "custom_category" to "কাস্টম ক্যাটেগরি",
        "create_category" to "ক্যাটেগরি যোগ করুন",
        "category_name" to "ক্যাটেগরির নাম",
        "select_type" to "ধরন নির্বাচন করুন",
        "reset_data" to "সমস্ত ডেটা রিসেট",
        "reset_warning" to "আপনি কি নিশ্চিত যে সমস্ত লেনদেনের তথ্য মুছে ফেলবেন? এটি চিরতরে মুছে যাবে।",
        "backup_restore" to "ব্যাকআপ এবং রিস্টোর",
        "backup_success" to "ব্যাকআপ সফলভাবে ফোনে সেভ করা হয়েছে!",
        "restore_success" to "ডেটা সফলভাবে রিস্টোর করা হয়েছে!",
        "backup_failed" to "ব্যাকআপ করা যায়নি",
        "restore_failed" to "রিস্টোর করা যায়নি",
        "all" to "সব",
        "filter" to "ফিল্টার",
        "search" to "খুঁজুন...",
        "weekly" to "সাপ্তাহিক ব্যয়",
        "monthly" to "মাসিক ব্যয়",
        "category_wise" to "ক্যাটেগরি-ভিত্তিক ব্যয়",
        "time_filter" to "সময় ফিল্টার",
        "export_report" to "রিপোর্ট এক্সপোর্ট",
        "share_report" to "রিপোর্ট শেয়ার করুন",
        "save_locally" to "ফোনে সেভ করুন",
        "pin_lock" to "পিন লক (৪ সংখ্যা)",
        "biometric_lock" to "বায়োমেট্রিক লক",
        "dark_mode" to "ডার্ক মোড",
        "language" to "ভাষা",
        "currency" to "মুদ্রা",
        "about_text" to "ব্যবহারকারীর গোপনীয়তা এবং নান্দনিক ডিজাইনের প্রতি সর্বোচ্চ নজর দিয়ে এই অ্যাপটি তৈরি করা হয়েছে। আপনার সম্পূর্ণ ফাইন্যান্সিয়াল ডেটা সম্পূর্ণ অফলাইনে সুরক্ষিত থাকে।",
        "about_author" to "তৈরি করেছেন: আব্দুল্লাহ আল ফাহিম"
    )

    fun translate(key: String, isBangla: Boolean): String {
        return if (isBangla) {
            BN[key] ?: EN[key] ?: key
        } else {
            EN[key] ?: key
        }
    }
}
